function demo()
    dhp = [...
        0,0,0,0;...
        0,0,0,0;...
        0,0,0,0;...
        0,0,0,0;...
        0,0,0,0 ...
    ];
    robotA = Robot3D(dhp);
    robot = robotA;

    wps = teach_waypoints();
    repeat_waypoints(robot, wps, 2);
end % #demo